config/routes.rb
Rails.application.routes.draw do


=begin
  get 'invoice_histories/index'
  get 'invoice_histories/create'
  get 'invoice_histories/new'
  get 'invoice_histories/destroy'
=end


  resources :invoice_histories do
    collection do
      get 'export'
    end
  end

  resources :requirements
  resources :invoice_statuses
  resources :invoices do
    collection do
      get 'display_pdf'
    end
  end
  get 'invoices/get_price/:id', to: 'invoices#get_price'
  get 'invoices/get_dam_canines/:id', to: 'invoices#get_dam_canines'
  get 'invoices/get_sire_canines/:id', to: 'invoices#get_sire_canines'
  get 'invoices/get_dams/:id', to: 'invoices#get_dams'
  get 'invoices/get_sires/:id', to: 'invoices#get_sires'
  get 'litters/get_dams/:id', to: 'litters#get_dams'
  get 'litters/get_sires/:id', to: 'litters#get_sires'
  resources :payment_methods
  resources :sales_people
  resources :sales_plans
  resources :canines
  resources :treatment_types
  resources :registration_companies
  resources :return_reasons
  resources :weight_categories
  resources :genders
  resources :litters
  resources :sires
  resources :dams
  resources :pictures
  resources :breeds
  resources :customers do
    collection do
      get 'phone_search'
    end
  end
  resources :breeders
  resources :brokers
  resources :veterinarians
  resources :peds

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users

  #get '/signup' => 'users#new'
  #post '/users' => 'users#create'
  #root to: 'sessions#new'
  root to: 'menu#index'

  get 'menu/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/invoice_statuses_controller.rb
class InvoiceStatusesController < ApplicationController
  before_action :set_invoice_status, only: [:show, :edit, :update, :destroy]

  # GET /invoice_statuses
  # GET /invoice_statuses.json
  def index
    @invoice_statuses = InvoiceStatus.all.order(:last_name)
  end

  # GET /invoice_statuses/1
  # GET /invoice_statuses/1.json
  def show
  end

  # GET /invoice_statuses/new
  def new
    @invoice_status = InvoiceStatus.new
  end

  # GET /invoice_statuses/1/edit
  def edit
  end

  # POST /invoice_statuses
  # POST /invoice_statuses.json
  def create
    @invoice_status = InvoiceStatus.new(invoice_status_params)

    respond_to do |format|
      if @invoice_status.save
        format.html { redirect_to @invoice_status, notice: 'Invoice status was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_status }
      else
        format.html { render :new }
        format.json { render json: @invoice_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_statuses/1
  # PATCH/PUT /invoice_statuses/1.json
  def update
    respond_to do |format|
      if @invoice_status.update(invoice_status_params)
        format.html { redirect_to @invoice_status, notice: 'Invoice status was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_status }
      else
        format.html { render :edit }
        format.json { render json: @invoice_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_statuses/1
  # DELETE /invoice_statuses/1.json
  def destroy
    @invoice_status.destroy
    respond_to do |format|
      format.html { redirect_to invoice_statuses_url, notice: 'Invoice status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_status
      @invoice_status = InvoiceStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_status_params
      params.require(:invoice_status).permit(:name)
    end
end

app/helpers/invoice_statuses_helper.rb
module InvoiceStatusesHelper
end

app/views/invoice_statuses/_form.html.erb
<%= form_with(model: invoice_status, local: true) do |form| %>
  <% if invoice_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice_status.errors.count, "error") %> prohibited this invoice_status from being saved:</h2>

      <ul>
      <% invoice_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :invoice_status_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoice_statuses/edit.html.erb
<%= render 'form', invoice_status: @invoice_status %>

<%= link_to 'Show', @invoice_status %> |
<%= link_to 'Back', invoice_statuses_path %>

app/views/invoice_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoice Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoice_statuses.each do |invoice_status| %>
      <tr>
        <td><%= invoice_status.name %></td>
        <td><%= link_to 'Show', invoice_status %></td>
        <td><%= link_to 'Edit', edit_invoice_status_path(invoice_status) %></td>
        <td><%= link_to 'Destroy', invoice_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice Status', new_invoice_status_path %>

app/views/invoice_statuses/new.html.erb
<h1>New Invoice Status</h1>

<%= render 'form', invoice_status: @invoice_status %>

<%= link_to 'Back', invoice_statuses_path %>

app/views/invoice_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @invoice_status.name %>
</p>

<%= link_to 'Edit', edit_invoice_status_path(@invoice_status) %> |
<%= link_to 'Back', invoice_statuses_path %>