config/routes.rb
Rails.application.routes.draw do


=begin
  get 'invoice_histories/index'
  get 'invoice_histories/create'
  get 'invoice_histories/new'
  get 'invoice_histories/destroy'
=end


  resources :invoice_histories do
    collection do
      get 'export'
    end
  end

  resources :requirements
  resources :invoice_statuses
  resources :invoices do
    collection do
      get 'display_pdf'
    end
  end
  get 'invoices/get_price/:id', to: 'invoices#get_price'
  get 'invoices/get_dam_canines/:id', to: 'invoices#get_dam_canines'
  get 'invoices/get_sire_canines/:id', to: 'invoices#get_sire_canines'
  get 'invoices/get_dams/:id', to: 'invoices#get_dams'
  get 'invoices/get_sires/:id', to: 'invoices#get_sires'
  get 'litters/get_dams/:id', to: 'litters#get_dams'
  get 'litters/get_sires/:id', to: 'litters#get_sires'
  resources :payment_methods
  resources :sales_people
  resources :sales_plans
  resources :canines
  resources :treatment_types
  resources :registration_companies
  resources :return_reasons
  resources :weight_categories
  resources :genders
  resources :litters
  resources :sires
  resources :dams
  resources :pictures
  resources :breeds
  resources :customers do
    collection do
      get 'phone_search'
    end
  end
  resources :breeders
  resources :brokers
  resources :veterinarians
  resources :peds

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users

  #get '/signup' => 'users#new'
  #post '/users' => 'users#create'
  #root to: 'sessions#new'
  root to: 'menu#index'

  get 'menu/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sire.rb
class Sire < ApplicationRecord
  belongs_to :breed
  belongs_to :breeder
  belongs_to :picture, optional: true
  #validates_presence_of :registration_number
end

app/controllers/sires_controller.rb
class SiresController < ApplicationController
  before_action :set_sire, only: [:show, :edit, :update, :destroy]

  # GET /sires
  # GET /sires.json
  def index
    @sires = Sire.all.order(registration_number: :asc)
  end

  # GET /sires/1
  # GET /sires/1.json
  def show
  end

  # GET /sires/new
  def new
    @sire = Sire.new
  end

  # GET /sires/1/edit
  def edit
  end

  # POST /sires
  # POST /sires.json
  def create
    @sire = Sire.new(sire_params)

    respond_to do |format|
      if @sire.save
        format.html { redirect_to @sire, notice: 'Sire was successfully created.' }
        format.json { render :show, status: :created, location: @sire }
      else
        format.html { render :new }
        format.json { render json: @sire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sires/1
  # PATCH/PUT /sires/1.json
  def update
    respond_to do |format|
      if @sire.update(sire_params)
        format.html { redirect_to @sire, notice: 'Sire was successfully updated.' }
        format.json { render :show, status: :ok, location: @sire }
      else
        format.html { render :edit }
        format.json { render json: @sire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sires/1
  # DELETE /sires/1.json
  def destroy
    @sire.destroy
    respond_to do |format|
      format.html { redirect_to sires_url, notice: 'Sire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sire
      @sire = Sire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sire_params
      params.require(:sire).permit(:name, :breed_id, :breeder_id, :registration_number, :comment, :picture_id)
    end
end

app/helpers/sires_helper.rb
module SiresHelper
end

app/views/sires/_form.html.erb
<div class="container-fluid">
<div style="background-color:lightgray">
<%= form_with(model: sire, local: true) do |form| %>
  <% if sire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sire.errors.count, "error") %> prohibited this sire from being saved:</h2>

      <ul>
      <% sire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">
    <br>
    <h2 align="center"> Sire Info</h2>
    <br>
    <div class="row" >
      <div class="col-sm-2"></div>
      <div class="col-sm-4">
        <%= form.label :registration_number %>
        <%= form.text_field :registration_number, id: :sire_registration_number, class: "form-control" %>
      </div>

      <div class="col-sm-4">
        <%= form.label :name %>
        <%= form.text_field :name, id: :sire_name, class: "form-control" %>
      </div>


      <div class="col-sm-2"></div>
    </div><br>

    <div class="row" >
      <div class="col-sm-2"></div>
      <div class="col-sm-4">
        <%= form.label :breed_id %>
        <%= form.collection_select(:breed_id, Breed.all, :id, :name,  {:include_blank => true}, {:class => 'form-control'}) %>
      </div>

      <div class="col-sm-4">
        <%= form.label :breeder_id %>
        <%= form.collection_select(:breeder_id, Breeder.all.order("last_name"), :id, :full_name, {:include_blank => true}, {:class => 'form-control'}) %>
      </div>
      <div class="col-sm-2"></div>
    </div><br>

    <div class="row" >
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <%= form.label :comment %>
        <%= form.text_area :comment, id: :sire_comment, class: "form-control" %>
        <div class="col-sm-2"></div>
      </div>
    </div><br>

    <div align="center">
      <div class="actions" >
        <%= form.submit :class => "btn btn-dark" %>
      </div>
    </div><br>
  <% end %>
  </div>
</div>
</div>

app/views/sires/edit.html.erb
<%= render 'form', sire: @sire %>

<%= link_to 'Show', @sire %> |
<%= link_to 'Back', sires_path %>

app/views/sires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sires</h1>
<div align="left">
  <%= link_to 'New Sire', new_sire_path, :class => "btn btn-dark" %>
</div><br>
<div class="container-fluid">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Registration Number</th>
      </tr>
    </thead>

    <tbody>
      <% @sires.each do |sire| %>
        <tr>
          <td><%= sire.name %></td>
          <td><%= link_to 'Show', sire, class: "btn btn-outline-dark btn-sm" %>
          <td><%= link_to 'Edit', edit_sire_path(sire), class: "btn btn-outline-dark btn-sm" %>
          <!--<td><%= link_to 'Destroy', sire, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


</div>

app/views/sires/new.html.erb
<%= render 'form', sire: @sire %>
<div class="container-fluid">
<%= link_to 'Back', sires_path %>
</div>

app/views/sires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sire.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @sire.breed.name %>
</p>

<p>
  <strong>Breeder:</strong>
  <%= @sire.breeder.company_name %>
</p>

<p>
  <strong>Registration number:</strong>
  <%= @sire.registration_number %>
</p>


<%= link_to 'Edit', edit_sire_path(@sire), :class => "btn btn-link" %> |
<%= link_to 'Back', sires_path, :class => "btn btn-link" %>