config/routes.rb
Rails.application.routes.draw do


=begin
  get 'invoice_histories/index'
  get 'invoice_histories/create'
  get 'invoice_histories/new'
  get 'invoice_histories/destroy'
=end


  resources :invoice_histories do
    collection do
      get 'export'
    end
  end

  resources :requirements
  resources :invoice_statuses
  resources :invoices do
    collection do
      get 'display_pdf'
    end
  end
  get 'invoices/get_price/:id', to: 'invoices#get_price'
  get 'invoices/get_dam_canines/:id', to: 'invoices#get_dam_canines'
  get 'invoices/get_sire_canines/:id', to: 'invoices#get_sire_canines'
  get 'invoices/get_dams/:id', to: 'invoices#get_dams'
  get 'invoices/get_sires/:id', to: 'invoices#get_sires'
  get 'litters/get_dams/:id', to: 'litters#get_dams'
  get 'litters/get_sires/:id', to: 'litters#get_sires'
  resources :payment_methods
  resources :sales_people
  resources :sales_plans
  resources :canines
  resources :treatment_types
  resources :registration_companies
  resources :return_reasons
  resources :weight_categories
  resources :genders
  resources :litters
  resources :sires
  resources :dams
  resources :pictures
  resources :breeds
  resources :customers do
    collection do
      get 'phone_search'
    end
  end
  resources :breeders
  resources :brokers
  resources :veterinarians
  resources :peds

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users

  #get '/signup' => 'users#new'
  #post '/users' => 'users#create'
  #root to: 'sessions#new'
  root to: 'menu#index'

  get 'menu/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/treatment_types_controller.rb
class TreatmentTypesController < ApplicationController
  before_action :set_treatment_type, only: [:show, :edit, :update, :destroy]

  # GET /treatment_types
  # GET /treatment_types.json
  def index
    @treatment_types = TreatmentType.all
  end

  # GET /treatment_types/1
  # GET /treatment_types/1.json
  def show
  end

  # GET /treatment_types/new
  def new
    @treatment_type = TreatmentType.new
  end

  # GET /treatment_types/1/edit
  def edit
  end

  # POST /treatment_types
  # POST /treatment_types.json
  def create
    @treatment_type = TreatmentType.new(treatment_type_params)

    respond_to do |format|
      if @treatment_type.save
        format.html { redirect_to @treatment_type, notice: 'Treatment type was successfully created.' }
        format.json { render :show, status: :created, location: @treatment_type }
      else
        format.html { render :new }
        format.json { render json: @treatment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatment_types/1
  # PATCH/PUT /treatment_types/1.json
  def update
    respond_to do |format|
      if @treatment_type.update(treatment_type_params)
        format.html { redirect_to @treatment_type, notice: 'Treatment type was successfully updated.' }
        format.json { render :show, status: :ok, location: @treatment_type }
      else
        format.html { render :edit }
        format.json { render json: @treatment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatment_types/1
  # DELETE /treatment_types/1.json
  def destroy
    @treatment_type.destroy
    respond_to do |format|
      format.html { redirect_to treatment_types_url, notice: 'Treatment type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment_type
      @treatment_type = TreatmentType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def treatment_type_params
      params.require(:treatment_type).permit(:name, :category)
    end
end

app/helpers/treatment_types_helper.rb
module TreatmentTypesHelper
end

app/views/treatment_types/_form.html.erb
<div class="container-fluid">
<div style="background-color:lightgray">
  <%= form_with(model: treatment_type, local: true) do |form| %>
    <% if treatment_type.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(treatment_type.errors.count, "error") %> prohibited this treatment_type from being saved:</h2>

        <ul>
        <% treatment_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="container-fluid">
      <br>
      <h2 align="center"> Treatment Types</h2>
      <br>
      <div class="row" >
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <%= form.label :name %>
          <%= form.text_field :name, id: :treatment_type_name, class: "form-control"  %>
        </div>
      <div class="col-sm-3"></div>
    </div><br>

    <div class="row" >
      <div class="col-sm-3"></div>
      <div class="col-sm-6">
        <%= form.label :category %>
        <%= form.text_field :category, id: :treatment_type_category, class: "form-control"  %>
      </div>
      <div class="col-sm-3"></div>
    </div><br>


    <div align="center">
      <div class="actions" >
        <%= form.submit :class => "btn btn-dark" %>
      </div>
    </div><br>

  <% end %>
</div>
</div>
</div>

app/views/treatment_types/edit.html.erb
<%= render 'form', treatment_type: @treatment_type %>

<%= link_to 'Show', @treatment_type %> |
<%= link_to 'Back', treatment_types_path %>

app/views/treatment_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Treatment Types</h1>
<div class="container-fluid">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
    </tr>
  </thead>

  <tbody>
    <% @treatment_types.each do |treatment_type| %>
      <tr>
        <td><%= treatment_type.name %></td>
        <td><%= treatment_type.category %></td>
        <td><%= link_to 'Show', treatment_type, class: "btn btn-outline-dark btn-sm" %></td>
        <td><%= link_to 'Edit', edit_treatment_type_path(treatment_type), class: "btn btn-outline-dark btn-sm" %></td>
        <!--<td><%= link_to 'Destroy', treatment_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Treatment Type', new_treatment_type_path, :class => "btn btn-dark" %>
</div>

app/views/treatment_types/new.html.erb
<%= render 'form', treatment_type: @treatment_type %>
<div class="container-fluid">
<%= link_to 'Back', treatment_types_path %>
</div>

app/views/treatment_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @treatment_type.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @treatment_type.category %>
</p>

<%= link_to 'Edit', edit_treatment_type_path(@treatment_type), :class => "btn btn-link" %> |
<%= link_to 'Back', treatment_types_path, :class => "btn btn-link" %>